import { AlertTriangle, Clock3, Gauge, Globe2, Radio, Thermometer, X } from 'lucide-react'
import type { CountryStats } from './types'

function value(number: number | undefined, suffix = '') { return number === undefined ? '—' : `${number}${suffix}` }

export function CountryDetailsPanel({ country, onClose, onViewSites, onZoom, onReset }: { country: CountryStats | null; onClose: () => void; onViewSites: () => void; onZoom: () => void; onReset: () => void }) {
  if (!country) return null
  return <aside className="country-details-panel"><div className="details-header"><div><span className="eyebrow">Country demonstration</span><h2>{country.name}</h2><p>{country.iso2} · {country.iso3} · {country.demo ? 'Demo monitoring' : 'Monitoring status unavailable'}</p></div><button className="icon-button" onClick={onClose} aria-label="Close country details"><X size={16} /></button></div><div className="country-demo-label"><Globe2 size={14} /> Simulated environmental data · fictional location</div><div className="country-stat-grid"><div><Radio size={14} /><strong>{country.siteCount}</strong><span>Demo sites</span></div><div><Radio size={14} /><strong>{country.sensorCount}</strong><span>Sensors</span></div><div><Gauge size={14} /><strong>{country.latestAqi ?? '—'}</strong><span>Average AQI</span></div><div><Thermometer size={14} /><strong>{value(country.latestTemperature, '°C')}</strong><span>Temperature</span></div><div><span className="summary-dot green" /><strong>{country.onlineCount}</strong><span>Online</span></div><div><span className="summary-dot amber" /><strong>{country.warningCount}</strong><span>Warning</span></div><div><span className="summary-dot red" /><strong>{country.criticalCount}</strong><span>Critical</span></div><div><span className="summary-dot offline" /><strong>{country.offlineCount}</strong><span>Offline</span></div></div><div className="country-alert-row"><AlertTriangle size={14} /> Active alerts <strong>{country.activeAlerts}</strong></div><div className="country-sync"><Clock3 size={13} /> Last sync {country.lastSync ? new Date(country.lastSync).toLocaleString([], { dateStyle: 'medium', timeStyle: 'short' }) : 'No recent reading'}</div><div className="country-panel-actions"><button className="button-primary" onClick={onViewSites}>View sites</button><button className="date-button" onClick={onZoom}>Zoom to country</button><button className="text-button" onClick={onReset}>Reset Global View</button></div><p className="details-disclaimer">This country marker represents a fictional demo location. Geo Nova does not currently monitor real-world countries or facilities.</p></aside>
}
