import { Search, SlidersHorizontal } from 'lucide-react'
import type { LiveStatus } from './types'

type Severity = 'all' | 'INFO' | 'WARNING' | 'CRITICAL'

export function GlobalFilters({ countries, sites, selectedCountry, selectedSite, status, severity, search, onCountryChange, onSiteChange, onStatusChange, onSeverityChange, onSearchChange, onReset }: { countries: Array<{ id: string; name: string }>; sites: Array<{ id: string; name: string }>; selectedCountry: string; selectedSite: string; status: 'all' | LiveStatus; severity: Severity; search: string; onCountryChange: (value: string) => void; onSiteChange: (value: string) => void; onStatusChange: (value: 'all' | LiveStatus) => void; onSeverityChange: (value: Severity) => void; onSearchChange: (value: string) => void; onReset: () => void }) {
  const statuses: Array<{ value: 'all' | LiveStatus; label: string }> = [{ value: 'all', label: 'All status' }, { value: 'normal', label: 'Normal' }, { value: 'warning', label: 'Warning' }, { value: 'critical', label: 'Critical' }, { value: 'offline', label: 'Offline' }]
  const severities: Array<{ value: Severity; label: string }> = [{ value: 'all', label: 'All alerts' }, { value: 'INFO', label: 'Info' }, { value: 'WARNING', label: 'Warning' }, { value: 'CRITICAL', label: 'Critical' }]
  return <div className="map-filters global-filters"><div className="filter-heading"><SlidersHorizontal size={14} /><span>Global filters</span></div><label className="filter-select"><span>Country</span><select value={selectedCountry} onChange={(event) => onCountryChange(event.target.value)}><option value="all">All demo countries</option>{countries.map((country) => <option key={country.id} value={country.id}>{country.name}</option>)}</select></label><label className="filter-select"><span>Industrial site</span><select value={selectedSite} onChange={(event) => onSiteChange(event.target.value)}><option value="all">All demo sites</option>{sites.map((site) => <option key={site.id} value={site.id}>{site.name}</option>)}</select></label><div className="status-filter"><span>Status</span><div className="status-filter-buttons">{statuses.map((item) => <button key={item.value} className={status === item.value ? 'selected' : ''} onClick={() => onStatusChange(item.value)}>{item.label}</button>)}</div></div><label className="filter-select"><span>Alert severity</span><select value={severity} onChange={(event) => onSeverityChange(event.target.value as Severity)}>{severities.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select></label><label className="search-filter"><Search size={14} /><input value={search} onChange={(event) => onSearchChange(event.target.value)} placeholder="Search country, site or sensor…" aria-label="Search country, site or sensor" /></label><button className="reset-global-button" onClick={onReset}>Reset Global View</button></div>
}
