import { AlertTriangle, BatteryMedium, Clock3, Droplets, Gauge, Thermometer, Wind, X } from 'lucide-react'
import type { ApiReading } from '../../services/api'
import { StatusBadge } from '../ui/StatusBadge'
import type { LiveSensor } from './types'

const statusText = { normal: 'Normal', warning: 'Warning', critical: 'Critical', offline: 'Offline' } as const
const typeText: Record<string, string> = { MULTI_GAS: 'Multi-gas monitor', AIR_QUALITY: 'Air-quality station', TEMPERATURE: 'Temperature node', HUMIDITY: 'Humidity node' }
function formatTime(value: string | null) { return value ? new Date(value).toLocaleString([], { dateStyle: 'medium', timeStyle: 'short' }) : 'No recent reading' }
function value(value: number | undefined, unit: string) { return value === undefined ? '—' : `${value.toFixed(1)} ${unit}` }

export function SensorDetailsPanel({ sensor, history, onClose }: { sensor: LiveSensor | null; history: ApiReading[]; onClose: () => void }) {
  if (!sensor) return <div className="sensor-details empty-details"><div className="details-empty-icon"><Gauge size={21} /></div><span className="eyebrow">Sensor details</span><h2>Select a sensor</h2><p>Choose a marker on the map to inspect its latest simulated readings and active alerts.</p></div>
  const reading = sensor.reading
  const status = statusText[sensor.liveStatus]
  const activeAlerts = sensor.alerts.filter((alert) => alert.status !== 'RESOLVED')
  return <aside className="sensor-details"><div className="details-header"><div><span className="eyebrow">Sensor details</span><h2>{sensor.name}</h2><p>{typeText[sensor.type] ?? sensor.type} · {sensor.location}</p><small className="sensor-id-label">ID {sensor.id}</small></div><button className="icon-button" onClick={onClose} aria-label="Close sensor details"><X size={16} /></button></div><div className="details-status-row"><StatusBadge severity={sensor.liveStatus === 'critical' ? 'critical' : sensor.liveStatus === 'warning' ? 'warning' : 'info'}>{status}</StatusBadge><span className="details-site">{sensor.site.country?.name ?? 'Demo country'} · {sensor.site.name}</span></div><div className="details-meta"><span><Clock3 size={13} /> {formatTime(sensor.lastSeenAt)}</span><span><BatteryMedium size={13} /> {sensor.batteryLevel}% battery</span></div><div className="reading-section"><div className="reading-section-heading"><span>Current reading</span><small>Simulated</small></div><div className="reading-grid"><div><Gauge size={14} /><span>AQI</span><strong>{reading?.aqi ?? '—'}</strong></div><div><Thermometer size={14} /><span>Temperature</span><strong>{value(reading?.temperature, '°C')}</strong></div><div><Droplets size={14} /><span>Humidity</span><strong>{value(reading?.humidity, '%')}</strong></div><div><Wind size={14} /><span>PM2.5</span><strong>{value(reading?.pm25, 'µg/m³')}</strong></div><div><Wind size={14} /><span>PM10</span><strong>{value(reading?.pm10, 'µg/m³')}</strong></div><div><span>CO</span><strong>{value(reading?.co, 'ppm')}</strong></div><div><span>H₂S</span><strong>{value(reading?.h2s, 'ppm')}</strong></div><div><span>VOC</span><strong>{value(reading?.voc, 'ppb')}</strong></div></div></div><div className="details-alerts"><div className="reading-section-heading"><span>Active alerts</span><small>{activeAlerts.length}</small></div>{activeAlerts.length ? activeAlerts.slice(0, 3).map((alert) => <div className="detail-alert" key={alert.id}><AlertTriangle size={14} /><div><strong>{alert.title}</strong><span>{alert.severity.toLowerCase()} · {alert.value.toFixed(1)} / demo threshold {alert.threshold}</span></div></div>) : <p className="details-clear">No active alert conditions for this sensor.</p>}</div><div className="recent-readings"><div className="reading-section-heading"><span>Recent readings</span><small>{history.length} records</small></div>{history.slice(-4).reverse().map((item) => <div className="recent-reading" key={item.id}><span>{new Date(item.timestamp).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</span><strong>AQI {item.aqi}</strong><span>PM2.5 {item.pm25.toFixed(1)}</span></div>)}</div><p className="details-disclaimer">Simulated demo data. Thresholds are not official safety limits.</p></aside>
}
